---
abstract: '(beta software) truncate HTML by percentage or character count while preserving well-formedness.'
author:
  - 'Ashley Pond V, C<< <ashley@cpan.org> >>.'
build_requires:
  Encode: 2
  File::Spec: 3
  Test::More: 0.5
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-Truncate
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Tagset: 3
  HTML::TokeParser: 2
  List::Util: 1
  perl: 5.8.0
version: 0.18
